services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./data:/www/assets
    restart: "unless-stopped"
    ports:
      - 8099:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
