services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "105" # to use hardware acceleration
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/primario/medias
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # to use hardware acceleration
    restart: "unless-stopped"
    ports:
      - 8096:8096
      - 8920:8920
